name: setup-codeql
description: Run CodeQL
inputs:
  version:
    description: CodeQL version
    required: false
    default: '2.23.0'
  platform:
    description: CodeQL platform
    required: false
    default: 'linux64'
  checksum:
    description: CodeQL SHA256 checksum
    required: false
    default: 'b5dec48ca1848cec8323816414830ea87edd3178ef5686c71946020a36cd5a61'
runs:
  using: composite
  steps:
    - uses: actions/cache@v5
      id: codeql-cache
      with:
        path: ~/.codeql/
        key: codeql|${{ inputs.version }}|${{ inputs.platform }}|${{ hashFiles('**/codeql-pack.lock.yml') }}
    - shell: bash
      if: steps.codeql-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/.codeql/bin/${{ inputs.version }}-${{ inputs.platform }}
        wget -q https://github.com/github/codeql-cli-binaries/releases/download/v${{ inputs.version }}/codeql-${{ inputs.platform }}.zip
        test ${{ inputs.checksum }} && echo "${{ inputs.checksum}}  codeql-${{ inputs.platform }}.zip" | sha256sum -c -
        unzip -q codeql-${{ inputs.platform }}.zip -d ~/.codeql/bin/${{ inputs.version }}-${{ inputs.platform }}
    - shell: bash
      run: |
        echo "$HOME/.codeql/bin/${{ inputs.version }}-${{ inputs.platform }}/codeql" >> "$GITHUB_PATH"
    - shell: bash
      if: steps.codeql-cache.outputs.cache-hit != 'true'
      run: |
        for lock in $(find . -name codeql-pack.lock.yml); do
          codeql pack install $(dirname $lock);
        done
